homepage:
  image:
    repository: ghcr.io/benphelps/homepage
    tag: latest
  enableRbac: true
  serviceAccount:
    name: homepage
    create: true
  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      labels:
        gethomepage.dev/enabled: "true"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: letsencrypt-issuer
        gethomepage.dev/name: "Homepage"
        gethomepage.dev/description: "A modern, secure, highly customizable application dashboard."
        gethomepage.dev/group: "A New Group"
        gethomepage.dev/icon: "homepage.png"
      hosts:
        - host: &host homepage.alexlebens.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: homepage-secret-tls
          hosts:
            - *host
  config:
    bookmarks:
      - External Services:
          - Digital Ocean:
              - abbr: DO
                href: https://cloud.digitalocean.com/projects/4c2f0ee4-0845-46f0-83a7-ec1646813cbf/resources?i=b869cc
          - Cloudflare:
              - abbr: CF
                href: https://dash.cloudflare.com/b76e303258b84076ee01fd0f515c0768
          - Pushover:
              - abbr: PO
                href: https://pushover.net
          - Dashboard Icons:
              - abbr: DI
                href: https://github.com/walkxcode/dashboard-icons/tree/main/png
          - Digital Ocean:
              - abbr: DO
                href: https://cloud.digitalocean.com/projects/4c2f0ee4-0845-46f0-83a7-ec1646813cbf/resources?i=b869cc

    services:
      - Services:
          - Vikunja:
              icon: vikunja.png
              description: Notes and Kanban
              href: https://vikunja.alexlebens.net

      - Platform:
          - ArgoCD:
              icon: argocd.png
              description: GitOps
              href: https://argocd.alexlebens.dev/applications
          - Gitea:
              icon: gitea.png
              description: Code repository
              href: https://gitea.alexlebens.dev/
          - Authentik:
              icon: authentik.png
              description: Identity management and provider
              href: https://authentik.alexlebens.dev/
          - Vault:
              icon: vault.png
              description: Secrets management
              href: https://vault.alexlebens.dev/

    widgets:
      - resources:
          backend: kubernetes
          expanded: true
          cpu: true
          memory: true
      - kubernetes:
          cluster:
            show: true
            cpu: true
            memory: true
            showLabel: true
            label: "cluster"
          nodes:
            show: true
            cpu: true
            memory: true
            showLabel: true
      - openmeteo:
          label: Denver
          latitude: 39.74
          longitude: -104.98
          timezone: America/Denver
          units: metric
          cache: 5
      - datetime:
          text_size: xl
          format:
            timeStyle: short
            hour12: false

    kubernetes:
      mode: cluster
