homepage:
  # Enable the ingress to expose Homepage to the network.
  ingress:
    main:
      enabled: true
      # labels:
      #   # This label will enable discover of this deployment in Homepage
      #   gethomepage.dev/enabled: "true"
      # annotations:
      #   # These annotations will configure how this deployment is shown in Homepage
      #   gethomepage.dev/name: "Homepage"
      #   gethomepage.dev/description: "A modern, secure, highly customizable application dashboard."
      #   gethomepage.dev/group: "A New Group"
      #   gethomepage.dev/icon: "homepage.png"
      # ingressClassName: "nginx"
      # hosts:
      #   - host: &host "homepage.local"
      #     paths:
      #       - path: /
      #         pathType: Prefix
      # tls:
      #   - hosts:
      #       - *host
  config:
    bookmarks:
      - Developer:
          - Github:
              - abbr: GH
                href: https://github.com/
    services:
      - My First Group:
          - My First Service:
              href: http://localhost/
              description: Homepage is awesome

      - My Second Group:
          - My Second Service:
              href: http://localhost/
              description: Homepage is the best

      - My Third Group:
          - My Third Service:
              href: http://localhost/
              description: Homepage is 😎
    widgets:
      - resources:
          backend: kubernetes
          expanded: true
          cpu: true
          memory: true
      - kubernetes:
          cluster:
            show: true
            cpu: true
            memory: true
            showLabel: true
            label: "cluster"
          nodes:
            show: true
            cpu: true
            memory: true
            showLabel: true
    kubernetes:
      mode: cluster