vikunja:
  frontend:
    apiUrl: https://vikunja.alexlebens.dev/
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: vikunja.alexlebens.dev
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - vikunja.alexlebens.dev
          secretName: vikunja-secret-tls
  api:
    config:
      auth:
        local:
          enabled: disabled
        openid:
          enabled: true
          redirecturl: https://vikunja.alexlebens.dev/auth/openid/
          providers:
            - name: authentik
              authurl: https://authentik.alexlebens.dev/application/o/vikunja/
              clientid: mi6i7dPwBIRdxomnqrZNsu3t7dagRqn4apS90XK2
              clientsecret: 0ZLnh8KroFInGQW9eKl0WAoxXfBrqpiRDePHUCuUCv9JqeVvLd5c1evFJY9EcwtEUP8HopEaIcZH6MBjJG4T5MbxZcXxob21oVIICuuaWEcte3lxyBrYsxPy6ElAVACl
      service:
        motd: Welcome to Vikunja
        frontendurl: https://vikunja.alexlebens.dev/
        timezone: MDT
      database:
        type: postgres
        user: vikunja
        host: postgresql
        database: vikunja
      cache:
        enabled: true
        type: redis
      redis:
        enabled: true
        host: redis
        db: 0
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: vikunja.alexlebens.dev
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - vikunja.alexlebens.dev
          secretName: vikunja-secret-tls
    envFrom:
      - name: VIKUNJA_DATABASE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: vikunja-credentials
            key: dbpassword
      - name: VIKUNJA_REDIS_PASSWORD
        valueFrom:
          secretKeyRef:
            name: vikunja-credentials
            key: redispassword
  postgresqlEnabled: true
  postgresql:
    postgresql:
      auth:
        username: vikunja
        database: vikunja
        existingSecret: vikunja-credentials
        secretKeys:
          adminPasswordKey: dbpassword
          userPasswordKey: dbpassword
          replicationPasswordKey: dbpassword
  redisEnabled: true
  redis:
    auth:
      enabled: true
      existingSecret: vikunja-credentials
      existingSecretPasswordKey: redispassword
