vikunja:
  frontend:
    apiUrl: https://vikunja.alexlebens.dev/api/v1
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: vikunja.alexlebens.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - vikunja.alexlebens.dev
          secretName: vikunja-secret-tls
  api:
    config:
      auth:
        local:
          enabled: disabled
        openid:
          enabled: true
          redirecturl: https://vikunja.alexlebens.dev/auth/openid/
          providers:
            - name: authentik
              authurl: https://authentik.alexlebens.dev/application/o/vikunja/
              clientid: mi6i7dPwBIRdxomnqrZNsu3t7dagRqn4apS90XK2
              clientsecret: 0ZLnh8KroFInGQW9eKl0WAoxXfBrqpiRDePHUCuUCv9JqeVvLd5c1evFJY9EcwtEUP8HopEaIcZH6MBjJG4T5MbxZcXxob21oVIICuuaWEcte3lxyBrYsxPy6ElAVACl
      service:
        motd: Welcome to Vikunja
        frontendurl: https://vikunja.alexlebens.dev/
        timezone: MST
      database:
        type: postgres
        user: vikunja
        password: supersecret
        host: vikunja-postgresql
        database: vikunja
      cache:
        enabled: true
        type: redis
      redis:
        enabled: true
        host: vikunja-redis-master:6379
        password: supersecret
        db: 0
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: vikunja.alexlebens.dev
          paths:
            - path: /api/v1
              pathType: Prefix
      tls:
        - hosts:
            - vikunja.alexlebens.dev
          secretName: vikunja-secret-tls
    persistence:
      vikunja-nginx:
        enabled: false
  postgresqlEnabled: true
  postgresql:
    postgresql:
      auth:
        username: vikunja
        database: vikunja
        existingSecret: vikunja-credentials
        secretKeys:
          adminPasswordKey: dbpassword
          userPasswordKey: dbpassword
          replicationPasswordKey: dbpassword
  redisEnabled: true
  redis:
    auth:
      enabled: true
      existingSecret: vikunja-credentials
      existingSecretPasswordKey: redispassword
    replica:
      replicaCount: 1
