vikunja:
  frontend:
    apiUrl: https://vikunja.alexlebens.dev/api/v1
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: vikunja.alexlebens.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - vikunja.alexlebens.dev
          secretName: vikunja-secret-tls
  api:
    config:
      service:
        frontendurl: https://vikunja.alexlebens.dev
        enableregistration: true
        timezone: MST
      auth:
        local:
          enabled: disabled
        openid:
          enabled: true
          redirecturl: https://vikunja.alexlebens.dev/auth/openid/
          providers:
            - name: authentik
              authurl: https://authentik.alexlebens.dev/application/o/vikunja/
              clientid: mi6i7dPwBIRdxomnqrZNsu3t7dagRqn4apS90XK2
              clientsecret: 0ZLnh8KroFInGQW9eKl0WAoxXfBrqpiRDePHUCuUCv9JqeVvLd5c1evFJY9EcwtEUP8HopEaIcZH6MBjJG4T5MbxZcXxob21oVIICuuaWEcte3lxyBrYsxPy6ElAVACl
      database:
        type: sqlite
        path: /sqlite/vikunja.db
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: vikunja.alexlebens.dev
          paths:
            - path: /api/v1/
              pathType: Prefix
      tls:
        - hosts:
            - vikunja.alexlebens.dev
          secretName: vikunja-secret-tls
    extraVolumeMounts:
      - mountPath: /sqlite/vikunja.db
        name: sqlite
  postgresqlEnabled: false
  redisEnabled: false
