apiVersion: workflows.tekton.dev/v1alpha1
kind: Workflow
metadata:
  name: main
  namespace: tekton-workflows
spec:
  triggers:
    - event:
        type: push
        secret:
          secretName: webhook-secret
          secretKey: token
      filters:
        # TODO Gitea doesn't have refs/head/ prefix, use gitRef after this is fixed
        # https://github.com/tektoncd/experimental/blob/3644c43377239bb639ec4191acc04fcf3aafb3f2/workflows/pkg/filters/filters.go#L44-L46
        gitRef:
          regex: '^main$'
        # custom:
        #   - cel: "body.ref.matches('^main$')"
      bindings:
        - name: git_url
          value: $(body.repository.clone_url)
        - name: git_revision
          value: $(body.after)
  params:
    - name: git_url
      default: https://github.com/AlexanderLebens/dev-infra
    - name: git_revision
      default: main
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: $(tt.params.git_url)
      - name: revision
        value: $(tt.params.git_revision)
      - name: pathInRepo
        value: .ci/main.yaml
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          storageClassName: do-block-storage
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 128Mi
