apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    email: {{ .Values.domain.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
      - selector:
          dnsZones:
          - '{{ .Values.domain.host }}'
          - '*.{{ .Values.domain.host }}'
        dns01:
          cloudflare:
            email: {{ .Values.domain.email }}
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
