apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-resources
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/argocd-resources
    repoURL: git@github.com:AlexanderLebens/dev-infra.git
    targetRevision: HEAD
    helm:
      parameters:
        - name: domain
          value: {{ .Values.domain }}
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true