apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-postgresql
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        username: authentik
        password: {{` "{{ .password }}" `}}
  data:
    - secretKey: postgresql-postgres-password
      remoteRef:
        key: /authentik/postgres
        property: postgresql-postgres-password
    - secretKey: postgresql-password
      remoteRef:
        key: /authentik/postgres
        property: postgresql-password
