apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-postgresql-secrets
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    template:
      engineVersion: v2
      data:
        username: authentik
        password: {{` "{{ .password }}" `}}
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None      
        key: /authentik/postgres
        property: password
