apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: 5.37.1
    helm:
      valuesObject:
        server.insecure: true
        configs.cm:
          resource.customizations:
            networking.k8s.io/Ingress:
              health.lua: |
                hs = {}
                hs.status = "Healthy"
                return hs
          resource.exclusions:
            - apiGroups:
              - cilium.io
              kinds:
              - CiliumIdentity
              clusters:
              - "*"
    chart: argo-cd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true