argo-cd:
  configs:
    params:
      server.insecure: true
    cm:
      # Patch for supporting traefik ingress health check
      resource.customizations: |
        networking.k8s.io/Ingress:
          health.lua: |
            hs = {}
            hs.status = "Healthy"
            return hs
      # Path to ignore Digital Ocean cilium resources
      resource.exclusions: |
        - apiGroups:
          - cilium.io
          kinds:
          - CiliumIdentity
          clusters:
          - "*"
  dex:
    enabled: false
  server:
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: argo-cd
          url: 'https://argoproj.github.io/argo-helm'