apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-oidc-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: secret
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: /gitea/oidc/secret
        property: secret
    - secretKey: key
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: /gitea/oidc/key
        property: key
