# Gitea
- path: gitea/admin
  data:
    - key: password
      length: 32
      special: true

- path: gitea/oidc/secret
  data:
    - key: secret
      length: 32
      special: true

- path: gitea/oidc/key
  data:
    - key: key
      length: 32
      special: true

# Tekton
- path: tekton/webhook
  data:
    - key: token
      length: 32
      special: false

# Authentik secret key
- path: authentik/key
  data:
    - key: token
      length: 32
      special: true

# Authentik postgres
- path: authentik/postgres
  data:
    - key: password
      length: 32
      special: false
