authentik:
  authentik:
    error_reporting:
      enabled: true
  postgresql:
    password: "7kNxJaHfuk"
  ingress:
    enabled: true
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      cert-manager.io/cluster-issuer: letsencrypt-issuer
    hosts:
      - host: &host authentik.alexlebens.dev
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: authentik-secret-tls
        hosts:
          - *host
  postgresql:
    enabled: true
    postgresqlPassword: "7kNxJaHfuk"
  redis:
    enabled: true
  prometheus:
    serviceMonitor:
      create: true
  envValueFrom:
    AUTHENTIK_SECRET_KEY:
      secretKeyRef:
        key: token
        name: authentik-key-secret
    AUTHENTIK_POSTGRESQL__PASSWORD:
      secretKeyRef:
        name: authentik-postgresql
        key: postgresql-password
