authentik:
  authentik:
    error_reporting:
      enabled: true
    postgresql:
      host: postgresql
      name: authentik
      user: authentik
      port: 5432
  ingress:
    enabled: true
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      cert-manager.io/cluster-issuer: letsencrypt-issuer
    hosts:
      - host: &host authentik.alexlebens.dev
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: authentik-secret-tls
        hosts:
          - *host
  postgresql:
    enabled: false
  redis:
    enabled: true
  prometheus:
    serviceMonitor:
      create: true
  envValueFrom:
    AUTHENTIK_SECRET_KEY:
      secretKeyRef:
        key: token
        name: authentik-key-secret
    AUTHENTIK_POSTGRESQL__PASSWORD:
      secretKeyRef:
        key: postgres-password
        name: authentik-postgresql
postgresql:
  customLivenessProbe:
    exec:
      command:
        - /bin/sh
        - "-c"
        - >-
          exec pg_isready -U "authentik" -d "dbname=authentik" -h
          127.0.0.1 -p 5432
    failureThreshold: 6
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  customReadinessProbe:
    exec:
      command:
        - /bin/sh
        - "-c"
        - "-e"
        - >
          exec pg_isready -U "authentik" -d "dbname=authentik" -h
          127.0.0.1 -p 5432

          [ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f
          /bitnami/postgresql/.initialized ]
    failureThreshold: 6
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  containerPorts:
    postgresql: 5432
  extraEnvVars:
    - name: POSTGRES_USER
      value: authentik
    - name: POSTGRES_DB
      value: authentik
  extraEnvVarsSecret:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          key: postgres-password
          name: authentik-postgresql
    - name: POSTGRES_POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          key: postgres-password
          name: authentik-postgresql
